// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gateway.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for command execution
type CommandRequest struct {
	// FQDN of the target device (e.g., router1.myCustomer.safabayar.net)
	Fqdn string `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// Username for authentication
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Password for authentication
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Command to execute
	Command string `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	// Protocol to use (ssh, telnet, netconf)
	Protocol             string   `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85acbde2a6adc437, []int{0}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *CommandRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CommandRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CommandRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

// Response message for command execution
type CommandResponse struct {
	// Command output
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Error message if any
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Exit code
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Session ID for tracking
	SessionId            string   `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85acbde2a6adc437, []int{1}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *CommandResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CommandResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CommandResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandRequest)(nil), "gateway.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "gateway.CommandResponse")
}

func init() {
	proto.RegisterFile("proto/gateway.proto", fileDescriptor_85acbde2a6adc437)
}

var fileDescriptor_85acbde2a6adc437 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x99, 0xef, 0xeb, 0xef, 0x01, 0x2b, 0x8c, 0xa2, 0x43, 0x45, 0x90, 0xe0, 0xa2, 0xab,
	0x44, 0xf4, 0x0e, 0x0c, 0x2a, 0x6e, 0xe3, 0xce, 0x4d, 0x99, 0x64, 0x4e, 0x6b, 0xc0, 0xe4, 0xa4,
	0xf3, 0x43, 0x5b, 0xbc, 0x0b, 0x17, 0x5e, 0xaf, 0x64, 0x32, 0x29, 0x88, 0x3b, 0x57, 0xc9, 0x73,
	0x5e, 0xce, 0xe1, 0xe1, 0x1d, 0x38, 0x69, 0x34, 0x59, 0x4a, 0xd6, 0xd2, 0xe2, 0x56, 0xee, 0x63,
	0x4f, 0x7c, 0x1c, 0x30, 0xfa, 0x64, 0x30, 0x4b, 0xa9, 0xaa, 0x64, 0xad, 0x32, 0xdc, 0x38, 0x34,
	0x96, 0x73, 0x18, 0xac, 0x36, 0xaa, 0x16, 0xec, 0x8a, 0x2d, 0xa6, 0x99, 0xff, 0xe7, 0x73, 0x98,
	0x38, 0x83, 0xba, 0x96, 0x15, 0x8a, 0x7f, 0x7e, 0x7e, 0xe0, 0x36, 0x6b, 0xa4, 0x31, 0x5b, 0xd2,
	0x4a, 0xfc, 0xef, 0xb2, 0x9e, 0xb9, 0x80, 0x71, 0xd1, 0x5d, 0x17, 0x03, 0x1f, 0xf5, 0xe8, 0xb7,
	0x5a, 0x95, 0x82, 0xde, 0xc5, 0x30, 0x6c, 0x05, 0x8e, 0x3e, 0xe0, 0xf8, 0xe0, 0x64, 0x1a, 0xaa,
	0x0d, 0xf2, 0x33, 0x18, 0x91, 0xb3, 0x8d, 0xb3, 0x41, 0x2b, 0x10, 0x3f, 0x85, 0x21, 0x6a, 0x4d,
	0x3a, 0x58, 0x75, 0xc0, 0x2f, 0x60, 0x8a, 0xbb, 0xd2, 0x2e, 0x0b, 0x52, 0xe8, 0x9d, 0x86, 0xd9,
	0xa4, 0x1d, 0xa4, 0xa4, 0x90, 0x5f, 0x02, 0x18, 0x34, 0xa6, 0xa4, 0x7a, 0x59, 0xf6, 0x5a, 0xd3,
	0x30, 0x79, 0x56, 0xb7, 0x5f, 0x0c, 0xc6, 0x4f, 0x5d, 0x3b, 0x3c, 0x85, 0xd9, 0xc3, 0x0e, 0x0b,
	0x67, 0x31, 0xf8, 0xf0, 0xf3, 0xb8, 0x2f, 0xf2, 0x67, 0x6b, 0x73, 0xf1, 0x3b, 0x08, 0xea, 0x8f,
	0x70, 0xf4, 0x62, 0x35, 0xca, 0xea, 0xef, 0x37, 0x16, 0xec, 0x86, 0xdd, 0x5f, 0xbf, 0x46, 0xeb,
	0xd2, 0xbe, 0xb9, 0x3c, 0x2e, 0xa8, 0x4a, 0x8c, 0x5c, 0xc9, 0x5c, 0xee, 0xa5, 0xee, 0x5f, 0x36,
	0xf1, 0xf5, 0xe5, 0x23, 0xff, 0xb9, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xb2, 0x34, 0xae,
	0xf7, 0x01, 0x00, 0x00,
}
