# Clabernetes Topology using Containerlab format
# This topology creates 2 SR Linux nodes with ClusterIP services only

apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: srlinux-demo
  namespace: default
spec:
  # Naming mode - non-prefixed to have simple service names like srl1, srl2
  naming: non-prefixed

  # Expose all ports via ClusterIP
  expose:
    disableAutoExpose: false
    exposeType: ClusterIP

  # Topology definition inline
  definition:
    containerlab: |
      name: srlinux-demo

      topology:
        mgmt:
          network: mgmt
          ipv4-subnet: 172.20.20.0/24

        nodes:
          srl1:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:latest
            type: ixrd3
            mgmt-ipv4: 172.20.20.11
            startup-config: |
              enter candidate
              / system management ssh admin-state enable server-ip 0.0.0.0
              / system management netconf admin-state enable server-ip 0.0.0.0
              / system aaa authentication admin-user admin password admin
              / interface ethernet-1/1 admin-state enable
              / interface ethernet-1/1 subinterface 0 admin-state enable ipv4 address 10.1.1.1/24
              / network-instance default interface ethernet-1/1.0
              commit stay

          srl2:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:latest
            type: ixrd3
            mgmt-ipv4: 172.20.20.12
            startup-config: |
              enter candidate
              / system management ssh admin-state enable server-ip 0.0.0.0
              / system management netconf admin-state enable server-ip 0.0.0.0
              / system aaa authentication admin-user admin password admin
              / interface ethernet-1/1 admin-state enable
              / interface ethernet-1/1 subinterface 0 admin-state enable ipv4 address 10.1.1.2/24
              / network-instance default interface ethernet-1/1.0
              commit stay

        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]

  # Image pull settings
  imagePull:
    pullThroughOverride: auto
