apiVersion: kne.googlecode.com/v1alpha1
kind: Topology
metadata:
  name: srlinux-demo
  namespace: default
spec:
  # Disable auto-expose to use ClusterIP only
  expose:
    disable: true

  # Define the topology
  topology:
    name: srlinux-demo

    nodes:
      # SR Linux Node 1
      srl1:
        kind: nokia_srlinux
        image: ghcr.io/nokia/srlinux:latest
        type: ixrd3
        config:
          startup-config: |
            set / system management ssh admin-state enable
            set / system management ssh server-ip 0.0.0.0
            set / system management netconf admin-state enable
            set / system management netconf server-ip 0.0.0.0
            set / system aaa authentication admin-user admin password admin
            set / interface ethernet-1/1 admin-state enable
            set / interface ethernet-1/1 subinterface 0 admin-state enable
            set / interface ethernet-1/1 subinterface 0 ipv4 address 10.1.1.1/24
            set / network-instance default interface ethernet-1/1.0
            commit save

      # SR Linux Node 2
      srl2:
        kind: nokia_srlinux
        image: ghcr.io/nokia/srlinux:latest
        type: ixrd3
        config:
          startup-config: |
            set / system management ssh admin-state enable
            set / system management ssh server-ip 0.0.0.0
            set / system management netconf admin-state enable
            set / system management netconf server-ip 0.0.0.0
            set / system aaa authentication admin-user admin password admin
            set / interface ethernet-1/1 admin-state enable
            set / interface ethernet-1/1 subinterface 0 admin-state enable
            set / interface ethernet-1/1 subinterface 0 ipv4 address 10.1.1.2/24
            set / network-instance default interface ethernet-1/1.0
            commit save

    links:
      # Link between srl1 and srl2
      - endpoints:
          - node: srl1
            interface: ethernet-1/1
          - node: srl2
            interface: ethernet-1/1
